-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME

-- This update was added 8-11-2021 (August 11th, 2021)

ALTER TABLE guilds
ADD logall varchar(255);
UPDATE guilds SET logall='false';

-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
