-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME

CREATE TABLE urlstopper (
    guildid varchar(255),
    message TEXT
);

-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME
-- DO NOT RUN THIS FILE IF YOU ARE INSTALLING THE BOT FOR THE FIRST TIME